"""
Combination grid over the model ready hERG drugs.

Six drugs clear the parameter gate: ESC, FLU, NOR, QUE, RIS, SER. Risperidone
carries 9-hydroxyrisperidone automatically, so RIS combinations are three or
four member in the model even when two or three are requested. That gives 15
pairs and 20 triples, not the 84 of the original design, because the four drugs
running through the stimulant and alpha-2 pathways are excluded until those
pathways are rebuilt against concentration response data.

TWO PASSES.

  Pass 1, arithmetic, instant. Combined block computed two ways, and dAPD90
  projected through the quadratic fitted to the measured engine response curve.
  This is triage, not a result.

  Pass 2, simulation, slow. Full 500 beat runs. Written incrementally so a
  crash does not lose the run.

THE ADDITIVITY TEST IS THE POINT OF THIS SCRIPT.

`excess_over_additive_ms` is the combination result minus the sum of its
members' individual effects. That is the only column that can distinguish a
real drug interaction from drugs simply adding up. An earlier version reported
`marginal_over_strongest_ms` instead, which merely recovered what the
non-dominant members contribute on their own and answered nothing.

On the projected values the excess runs +0.08 to +2.90 ms across all 35
combinations, mean +0.95, against a 0.5 ms measurement grid. It correlates with
total block at r = 0.914 and not with drug identity, so its source is
arithmetic rather than pharmacological: independent binding sites combine block
sub-additively, the block to APD90 response is supralinear, and the curvature
slightly outweighs the sub-additivity. Any two drugs summing to the same total
block give the same excess.

Pass 2 tests this by simulation rather than projection, which matters because
the projection is generated by the same curve that produces the excess.

BINDING SITE BOUNDS. Combined block is reported under both models:

  independent sites   1 - prod(1 - b_i)          upper bound
  single shared site  sum(a_i) / (1 + sum(a_i))  lower bound, a_i = C_i / IC50_i

Margulis M, Sorota S. Additive effects of combined application of multiple hERG
blockers. J Cardiovasc Pharmacol 2008;51(6). Tested combinations across three
distinct binding sites and found no synergy, with measured block sometimes
slightly BELOW additive. Independent sites is therefore a genuine upper bound.
Across this drug set the two models differ by at most 1.2 percentage points of
block, about 2.5 ms, so the choice is not load bearing. Report both anyway.

NO CLINICAL CONVERSION IS APPLIED, AND NONE IS AVAILABLE.

An earlier version divided every result by 1.5 and compared the product against
the ICH E14 10 ms threshold. Both steps were wrong and have been removed.
src/calibrate.py tested the correction against all three FDA quetiapine anchors:

  400 mg/day   model 4.5 ms   FDA ddQTcF 5.4 ms   ratio 0.839
  600 mg/day   model 8.5 ms   FDA ddQTcF 6.8 ms   ratio 1.256
  800 mg/day   model 9.5 ms   FDA ddQTcF 6.9 ms   ratio 1.382

The ratio crosses 1.0, so the model under-predicts at low exposure and
over-predicts at high. No constant factor fits a bias that changes sign. A
linear fit appears excellent but is fitting an artifact: FDA's own exposure
response model carries a structural intercept of about 4 ms at zero drug, which
the fit inherits, and with three points and two free parameters it has one
degree of freedom.

What survives is an agreement check, not a conversion. Model dAPD90 and FDA
predicted ddQTcF agree within a factor of 1.4 across the tested range with no
consistent direction of bias. That is a reasonable order of magnitude
validation for a single cell simulation against a regulatory population model
in a different measurement. It cannot produce adjusted clinical values, and the
ICH E14 threshold applies to ddQTcF, not to single cell APD90.

Results are reported as raw dAPD90, ranked. See results/calibration_memo.md.

Usage:
    cd src && python3 combination_grid.py            # triage then full runs
    cd src && python3 combination_grid.py --triage   # arithmetic only
    cd src && python3 combination_grid.py --pm       # escitalopram poor metabolizer

Output: results/combination_grid.csv  (or _pm.csv)
"""

import argparse
import time
from itertools import combinations
from pathlib import Path

import numpy as np
import pandas as pd

import ord_model as M

BASELINE = 263.6
N_BEATS = 500
CL = 1000.0

# Quadratic fitted to the measured engine response, FORCED THROUGH THE ORIGIN,
# RESTRICTED to block at or below 25 percent. 53 measured points: the 35 grid
# combinations, the 6 singles, the escitalopram sensitivity runs, and the low
# block points from results/curve_block_apd90.csv.
#
#   mean error -0.008 ms, MAE 0.111 ms, max 0.34 ms
#
# That is below the 0.5 ms measurement grid at every point, so projection can
# replace simulation for triage in this range.
#
# The restriction is deliberate. A single quadratic cannot describe both this
# range and the 30 to 70 percent region. Fitted across the full 1.5 to 70
# percent span it carries +0.30 ms mean bias and 0.84 ms MAE. For block above
# 30 percent use [0.01966, 1.4673, 0.0] and expect about a millisecond of
# error, or simulate directly.
#
# Validated slightly past its ceiling: escitalopram at CYP2C19 poor metabolizer
# exposure, 26.49 percent block, projects 51.4 ms against a measured 51.6.
#
# Fit history. [0.02618, 0.9841, 5.141] was fitted from 5 percent upward with no
# origin constraint and carried a spurious +5.14 ms intercept, overestimating by
# up to 4.2 ms below 5 percent block. [0.02086, 1.3957, 0.0] fixed the intercept
# but was fitted before the combination grid existed and underestimated
# systematically: +1.18 ms mean on the 35 combinations, +0.68 on the singles.
CURVE = [0.01211, 1.6184, 0.0]
CURVE_MAX_BLOCK = 30.0

# Poweleit 2023 Table 3 measured Cmax ratio, CYP2C19 poor vs normal metabolizer.
PM_RATIO = 186.0 / 73.73


def project(block_pct):
    if block_pct > CURVE_MAX_BLOCK:
        return np.nan
    return float(np.polyval(CURVE, block_pct))


def members(codes, params):
    """Expand to actual simulated members, so RIS pulls in 9OHRIS."""
    return list(M.expand_combination({c: "therapeutic" for c in codes}, params))


def block_bounds(codes, params, esc_scale=1.0):
    """Combined block under both binding site models, as percentages."""
    a = []
    for code in members(codes, params):
        dp = params[code]
        fc = M.free_cmax_nM(dp)
        if fc is None or dp["ic50_nM"] is None:
            continue
        if code == "ESC":
            fc *= esc_scale
        a.append(fc / dp["ic50_nM"])
    independent = (1.0 - np.prod([1.0 / (1.0 + x) for x in a])) * 100
    shared = (sum(a) / (1.0 + sum(a))) * 100
    return independent, shared


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--triage", action="store_true",
                    help="arithmetic only, no simulation")
    ap.add_argument("--pm", action="store_true",
                    help="escitalopram at CYP2C19 poor metabolizer exposure")
    args = ap.parse_args()

    params = M.load_drug_params()
    codes = M.model_ready_codes(params)
    esc_scale = PM_RATIO if args.pm else 1.0
    tag = "_pm" if args.pm else ""
    out = Path(__file__).resolve().parent.parent / "results" / f"combination_grid{tag}.csv"

    # Single drug projections, needed for the additivity test.
    singles = {c: project(block_bounds((c,), params, esc_scale)[0]) for c in codes}

    combos = [c for n in (2, 3) for c in combinations(codes, n)]
    print(f"Model ready drugs: {codes}")
    if args.pm:
        print(f"Escitalopram scaled {PM_RATIO:.3f}x for CYP2C19 poor metabolizer")
    print(f"{len(combos)} combinations: "
          f"{sum(1 for c in combos if len(c) == 2)} pairs, "
          f"{sum(1 for c in combos if len(c) == 3)} triples")
    print("Single drug projections, ms dAPD90: "
          + ", ".join(f"{c} {singles[c]:.1f}" for c in codes) + "\n")

    # ---- Pass 1, arithmetic ----
    rows = []
    for c in combos:
        ind, sh = block_bounds(c, params, esc_scale)
        proj = project(ind)
        ssum = sum(singles[k] for k in c)
        rows.append({
            "combination": "+".join(c),
            "n_requested": len(c),
            "simulated_members": "+".join(members(c, params)),
            "block_independent_pct": round(ind, 3),
            "block_shared_site_pct": round(sh, 3),
            "block_bound_width_pp": round(ind - sh, 3),
            "projected_dAPD90_ms": round(proj, 1),
            "pct_of_baseline_APD90": round(proj / BASELINE * 100, 2),
            "sum_of_singles_ms": round(ssum, 1),
            "excess_over_additive_ms": round(proj - ssum, 2),
            "excess_pct": round((proj - ssum) / ssum * 100, 1),
        })
    df = pd.DataFrame(rows).sort_values("block_independent_pct", ascending=False)

    print("PASS 1, ARITHMETIC TRIAGE. Projected, not simulated. Raw dAPD90.")
    print(f"{'combination':<20}{'block %':>9}{'bnd pp':>8}{'proj ms':>9}"
          f"{'% base':>8}{'sum solo':>10}{'excess':>9}{'excess %':>10}")
    for _, r in df.iterrows():
        print(f"{r['combination']:<20}{r['block_independent_pct']:>9.2f}"
              f"{r['block_bound_width_pp']:>8.3f}{r['projected_dAPD90_ms']:>9.1f}"
              f"{r['pct_of_baseline_APD90']:>8.2f}{r['sum_of_singles_ms']:>10.1f}"
              f"{r['excess_over_additive_ms']:>+9.2f}{r['excess_pct']:>+9.1f}%")

    ex = df["excess_over_additive_ms"]
    corr = np.corrcoef(df["block_independent_pct"], ex)[0, 1]
    print(f"\nExcess over additive: {ex.min():+.2f} to {ex.max():+.2f} ms, "
          f"mean {ex.mean():+.2f}, against a 0.5 ms measurement grid.")
    print(f"Correlation between total block and excess: r = {corr:.4f}")
    print("If that correlation is high and the excess is small, the deviation "
          "from")
    print("additivity is a property of the response curve, not a drug "
          "interaction:")
    print("independent sites combine block sub-additively while the block to "
          "APD90")
    print("curve is supralinear, and the curvature slightly outweighs it.")
    print(f"\nWidest binding site bound: {df['block_bound_width_pp'].max():.3f} "
          f"percentage points.")
    print("Margulis 2008 found no synergy experimentally, so the independent "
          "value is an")
    print("upper bound. No clinical threshold is applied; see the module "
          "docstring.")

    out.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(out, index=False)
    print(f"\nWrote {out}")

    if args.triage:
        print("\nTriage only. Rerun without --triage to simulate.")
        return

    # ---- Pass 2, simulation ----
    # The projected excess is generated by the same curve that produces it, so
    # simulation is the only way to test additivity independently. Single drugs
    # are simulated first so the comparison uses measured values on both sides.
    print(f"\nPASS 2, SIMULATION.")
    print(f"Simulating {len(codes)} singles first, then {len(df)} combinations, "
          f"at {N_BEATS} beats.")
    print(f"{'run':<20}{'block %':>9}{'sim ms':>9}{'proj ms':>9}{'err':>7}"
          f"{'elapsed':>9}")

    t0 = time.time()
    sim_singles = {}
    for c in codes:
        combo = {c: "therapeutic"}
        if args.pm and c == "ESC":
            combo["ESC"] = M.free_cmax_nM(params["ESC"]) * PM_RATIO
        r = M.run_simulation(combo, n_beats=N_BEATS, CL=CL, verbose=False)
        d = r["APD90"] - BASELINE
        sim_singles[c] = d
        print(f"{c:<20}{r['IKr_block_pct']:>9.2f}{d:>9.1f}{singles[c]:>9.1f}"
              f"{d - singles[c]:>+7.1f}{time.time() - t0:>8.0f}s", flush=True)

    sims = []
    for _, r in df.iterrows():
        codes_in = r["combination"].split("+")
        combo = {c: "therapeutic" for c in codes_in}
        if args.pm and "ESC" in combo:
            combo["ESC"] = M.free_cmax_nM(params["ESC"]) * PM_RATIO
        res = M.run_simulation(combo, n_beats=N_BEATS, CL=CL, verbose=False)
        d = res["APD90"] - BASELINE
        ssum_sim = sum(sim_singles[c] for c in codes_in)
        sims.append({
            "combination": r["combination"],
            "sim_block_pct": round(res["IKr_block_pct"], 3),
            "APD90_ms": round(res["APD90"], 2),
            "dAPD90_ms": round(d, 2),
            "sim_pct_of_baseline": round(d / BASELINE * 100, 2),
            "sim_sum_of_singles_ms": round(ssum_sim, 2),
            "sim_excess_over_additive_ms": round(d - ssum_sim, 2),
            "projection_error_ms": round(d - r["projected_dAPD90_ms"], 2),
        })
        print(f"{r['combination']:<20}{res['IKr_block_pct']:>9.2f}{d:>9.1f}"
              f"{r['projected_dAPD90_ms']:>9.1f}"
              f"{d - r['projected_dAPD90_ms']:>+7.1f}"
              f"{time.time() - t0:>8.0f}s", flush=True)
        df.merge(pd.DataFrame(sims), on="combination", how="left").to_csv(out, index=False)

    final = df.merge(pd.DataFrame(sims), on="combination", how="left")
    final.to_csv(out, index=False)

    err = final["projection_error_ms"].abs()
    sx = final["sim_excess_over_additive_ms"]
    print(f"\nWrote {out}")
    print(f"\nSIMULATED excess over additive: {sx.min():+.2f} to {sx.max():+.2f} "
          f"ms, mean {sx.mean():+.2f}")
    print(f"PROJECTED excess was: {ex.min():+.2f} to {ex.max():+.2f} ms, "
          f"mean {ex.mean():+.2f}")
    print("If those agree, additivity is measured rather than inferred from the "
          "curve.")
    print(f"\nQuadratic projection error across combinations: mean "
          f"{err.mean():.2f} ms, max {err.max():.2f} ms.")
    print("The curve was fitted on single drug runs only. This is its first "
          "test on")
    print("multi drug combinations.")


if __name__ == "__main__":
    main()