"""
generate_sim_data.py — CardioSafe Pediatric
============================================
Reads results/risk_grid_results.csv and results/faers/faers_combo_ror.csv
and regenerates the hardcoded JS data block in docs/clinical_sim.html.

Run after any risk_grid.py rerun to keep the simulator in sync.

Usage:
    python3 src/generate_sim_data.py
    python3 src/generate_sim_data.py --dry-run   # print JS only, don't patch file
"""

import sys
import re
import csv
import json
import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GRID_CSV   = ROOT / "results" / "risk_grid_results.csv"
FAERS_CSV  = ROOT / "results" / "faers" / "faers_combo_ror.csv"
SIM_HTML   = ROOT / "docs" / "clinical_sim.html"

DRUG_CODES = {
    "Methylphenidate": "MPH",
    "Amphetamine":     "AMP",
    "Risperidone":     "RIS",
    "Quetiapine":      "QUE",
    "Aripiprazole":    "ARI",
    "Sertraline":      "SER",
    "Fluoxetine":      "FLU",
    "Escitalopram":    "ESC",
    "Clonidine":       "CLO",
    "Guanfacine":      "GUA",
    "Imipramine":      "IMI",
    "Nortriptyline":   "NOR",
}

def canonical_key(drug_a, drug_b):
    """Canonical sort order for pair key."""
    codes = sorted([drug_a, drug_b])
    return f"{codes[0]}+{codes[1]}"

def load_grid():
    """Load pairwise delta-QTc and IKr% from risk_grid_results.csv."""
    dqtc = {}
    ikr  = {}
    if not GRID_CSV.exists():
        print(f"ERROR: {GRID_CSV} not found", file=sys.stderr)
        sys.exit(1)

    with open(GRID_CSV) as f:
        reader = csv.DictReader(f)
        for row in reader:
            combo_str = row.get("combination", row.get("Combination", "")).strip()
            drugs = [d.strip() for d in combo_str.split("+")]
            if len(drugs) != 2:
                continue  # skip triples

            # combination field already uses codes (MPH, ARI, etc.)
            # but fall back to full-name lookup if needed
            a = DRUG_CODES.get(drugs[0], drugs[0])
            b = DRUG_CODES.get(drugs[1], drugs[1])

            try:
                dq = float(row.get("ΔQTc_ms", row.get("delta_qtc", row.get("dQTc", row.get("ΔQTc", 0)))))
                ik = float(row.get("IKr_block_pct", row.get("ikr_block_pct", row.get("IKr_block", row.get("ikr_block", 0)))))
            except (ValueError, KeyError):
                continue

            key = canonical_key(a, b)
            dqtc[key] = round(dq, 1)
            ikr[key]  = round(ik, 2)

    print(f"Loaded {len(dqtc)} pairwise combinations from risk_grid_results.csv")
    return dqtc, ikr

def load_faers():
    """Load FAERS ROR data from faers_combo_ror.csv."""
    ror     = {}
    signals = set()
    if not FAERS_CSV.exists():
        print(f"WARNING: {FAERS_CSV} not found — FAERS data will be empty", file=sys.stderr)
        return ror, signals

    with open(FAERS_CSV) as f:
        reader = csv.DictReader(f)
        for row in reader:
            combo = row.get("combo", row.get("combination", "")).strip()
            # combo is like "Methylphenidate+Sertraline" or "MPH+SER"
            parts = combo.split("+")
            if len(parts) != 2:
                continue
            a = DRUG_CODES.get(parts[0].strip(), parts[0].strip())
            b = DRUG_CODES.get(parts[1].strip(), parts[1].strip())
            key = canonical_key(a, b)

            try:
                ror_val = float(row.get("ROR", row.get("ror", 0)))
                ci_lo   = float(row.get("CI_lo", row.get("ci_lo", 0)))
            except (ValueError, KeyError):
                continue

            ror[key] = round(ror_val, 2)
            if ci_lo > 1.0:
                signals.add(key)

    print(f"Loaded {len(ror)} FAERS ROR values, {len(signals)} signals")
    return ror, signals

def build_js(dqtc, ikr, ror, signals):
    """Build the JS data block string."""

    def js_obj(d):
        lines = []
        for k, v in sorted(d.items()):
            lines.append(f'  "{k}":{json.dumps(v)}')
        return "{\n" + ",\n".join(lines) + "\n}"

    def js_set(s):
        items = sorted(s)
        quoted = [f'"{x}"' for x in items]
        return "new Set([\n  " + ",\n  ".join(quoted) + "\n])"

    js = f"""// ── AUTO-GENERATED by src/generate_sim_data.py — do not edit manually ──
// Source: results/risk_grid_results.csv + results/faers/faers_combo_ror.csv
// Run `python3 src/generate_sim_data.py` to regenerate after a new risk_grid run.

const DQTC = {js_obj(dqtc)};

const IKR = {js_obj(ikr)};

const FAERS_ROR = {js_obj({k: v for k, v in ror.items() if k in signals})};

const FAERS_SIGNAL = {js_set(signals)};"""

    return js

def patch_html(js_block, dry_run=False):
    """Replace the data block in clinical_sim.html."""
    if not SIM_HTML.exists():
        print(f"ERROR: {SIM_HTML} not found", file=sys.stderr)
        sys.exit(1)

    content = SIM_HTML.read_text()

    # Find the block between markers
    start_marker = "// ── DATA ──"
    end_marker   = "// ── STATE ──"

    start_idx = content.find(start_marker)
    end_idx   = content.find(end_marker)

    if start_idx == -1 or end_idx == -1:
        # Fall back: replace between known variable declarations
        # Find first const DQTC and last const FAERS_SIGNAL
        start_idx = content.find("const DQTC")
        # Find the closing }; after FAERS_SIGNAL
        faers_start = content.find("const FAERS_SIGNAL")
        end_idx = content.find("// ── STATE ──", faers_start)
        if start_idx == -1:
            print("ERROR: could not find data block in clinical_sim.html", file=sys.stderr)
            print("Printing JS to stdout instead:")
            print(js_block)
            return

    new_content = (
        content[:start_idx] +
        start_marker + "\n" +
        js_block + "\n\n" +
        content[end_idx:]
    )

    if dry_run:
        print("── DRY RUN — JS block that would be inserted ──")
        print(js_block)
        return

    SIM_HTML.write_text(new_content)
    print(f"Patched: {SIM_HTML}")
    entry_count = js_block.count('\n  "')
    print(f"  DQTC entries:   {entry_count}")

def main():
    parser = argparse.ArgumentParser(description="Regenerate clinical simulator data from risk grid results")
    parser.add_argument("--dry-run", action="store_true", help="Print JS only, do not patch HTML")
    args = parser.parse_args()

    print("CardioSafe Pediatric — Clinical Simulator Data Generator")
    print(f"Grid CSV:  {GRID_CSV}")
    print(f"FAERS CSV: {FAERS_CSV}")
    print(f"Sim HTML:  {SIM_HTML}")
    print()

    dqtc, ikr   = load_grid()
    ror, signals = load_faers()

    # Sanity check
    if len(dqtc) < 60:
        print(f"WARNING: only {len(dqtc)} pairs loaded — expected ~66. Check CSV format.")

    js_block = build_js(dqtc, ikr, ror, signals)
    patch_html(js_block, dry_run=args.dry_run)

    print()
    print("Done. Open docs/clinical_sim.html to verify.")
    print("Commit: git add docs/clinical_sim.html && git commit -m 'feat: update simulator data from 500-beat risk grid'")

if __name__ == "__main__":
    main()